name=NiusWireless
version=1.0.0
author=NiusLab
maintainer=NiusLab <support@niuslab.dev>
sentence=Expandable Arduino library for wireless and RF modules.
paragraph=Supports RFID-RC522 (MFRC522), NRF24L01, HC-12, HC-06/HC-05, PN532 NFC modules. Compatible with AVR, SAMD, ESP32, NRF52, STM32, RP2040, Renesas (UNO R4) and more.
category=Communication
url=https://github.com/NiusLab/NiusWireless
architectures=*
includes=NiusWireless.h
